# Generated by Django 4.2.7 on 2023-11-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=255)),
                ('message', models.CharField(default='', max_length=255)),
                ('issuccess', models.BooleanField(default=False)),
            ],
        ),
    ]
