# Generated by Django 4.2.7 on 2023-11-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_globalpostcount_post_count_post_global_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
